export const DataProjects = [
    {
      id: 1,
      title: "dice",
      imageSrc: require("../images/dice.jpg"),
      description: " This is a game ",
      skills: "Html, Css, JavaScript",
      source: "https://github.com/Nasrin-Rahmani/Dice-game.git",
    },
    {
      id: 2,
      title: "mycv",
      imageSrc: require("../images/mycv.PNG"),
      description: " this is my CV",
      skills: "Html & Css",
      source: "https://github.com/Nasrin-Rahmani/My-CV.git",
    },
    {
      id: 3,
      title: "BitDog",
      imageSrc: require("../images/bit-dog.jpg"),
      description: " This is a project with bs",
      skills: "Html & Css",
      source: "https://github.com/Nasrin-Rahmani/bit-dog.git",
    },
    {
      id: 4,
      title: "Halloween",
      imageSrc: require("../images/halloween.PNG"),
      description: " this is about halloween day ",
      skills: "Html & Css",
      source: "https://github.com/Nasrin-Rahmani/halloween.git",
    },
    {
      id: 5,
      title: "Show Model",
      imageSrc: require("../images/show.jpg"),
      description: " this is a project that show various model ",
      skills: "Html, Css, JavaScript",
      source: "https://github.com/Nasrin-Rahmani/show-model.git",
    },
    {
      id: 6,
      title: "Expenses",
      imageSrc: require("../images/expenses.jpg"),
      description: " this is a list of computer with date and price",
      skills: "Html, Css, Js & React",
      source: "https://github.com/Nasrin-Rahmani/expenses.git",
    },
    {
      id: 7,
      title: "Programmer",
      imageSrc: require("../images/pro.PNG"),
      description: " this is a project about my skills ",
      skills: "Html & Css",
      source: "https://github.com/Nasrin-Rahmani/programmer.git",
    },
    {
      id: 8,
      title: "Scop chain",
      description: " this is a project that create by js  ",
      skills: "Html, Css, JavaScript",
      source: "https://github.com/Nasrin-Rahmani/scop-chain.git",
    },
    {
      id: 9,
      title: "Guess Number",
      imageSrc: require("../images/guss.jpg"),
      description: " this is a game that can play",
      skills: "Html, Css, JavaScript",
      source: "https://github.com/Nasrin-Rahmani/Guss-Number.git",
    },
   
    {
      id: 10,
      title: "Timer Challenge",
      imageSrc: require("../images/timer.jpg"),
      description: " this is a project that start & puase a game in specific",
      skills: "Html, Css, React",
      source: "https://github.com/Nasrin-Rahmani/Timer-Challenge.git",
    },
    {
      id: 11,
      title: "doctors",
      imageSrc: require("../images/doctors.jpg"),
      description: " this is a project show a list of doctors",
      skills: "Html, Css, React",
      source: "https://github.com/Nasrin-Rahmani/doctors.git",
    },
  
    {
      id: 12,
      title: "Counter project",
      imageSrc: require("../images/counter.PNG"),
      description: " this is a couter and helps you count",
      skills: "Html, Css, React",
      source: "https://github.com/Nasrin-Rahmani/Counter.git",
    },
    
  ];